FYLO_Backend/urls.py
"""
Definition of urls for FYLO_Backend.
"""

from django.urls import path
from django.contrib import admin
from app import views
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', views.index, name='index'),
    path('bases/', views.BaseListView.as_view(), name='bases'),
    path('base/<int:pk>', views.BaseDetailView.as_view(), name='base-detail'),
    path('battalions/', views.BattalionListView.as_view(), name='battalions'),
    path('battalion/<int:pk>', views.BattalionDetailView.as_view(), name='battalion-detail'),
    path('brigade/<int:pk>', views.BrigadeDetailView.as_view(), name='brigade-detail'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('pdf/upload/', views.upload_pdf, name='upload_pdf'),
    path('api/', include('api.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('file/', views.getFile),
    path('base/', views.getBase.as_view()),
    path('base/add/', views.addBase),
    path('user/', views.getUser),
    path('user/add/', views.addUser.as_view()),
]

app/models.py
"""
Definition of models.
"""

from re import T
from django.db import models
from django.urls import reverse

# Create your models here.

class Base(models.Model):
    name = models.CharField(max_length=200, help_text='Enter the base.')

    location = models.CharField(max_length=200, help_text='Enter the state for this base.')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('base-detail', args=[str(self.id)])

class Command(models.Model):
    name = models.CharField(max_length=200, help_text='Enter an Army Command (e.g. TRADOC)')

    def __str__(self):
        """Strting for representing the Model object."""
        return self.name

class Brigade(models.Model):
    """Model representing a Brigade"""
    name = models.CharField(max_length=200, help_text='Enter the Brigade.')
    
    command = models.ForeignKey(Command, on_delete=models.RESTRICT, null=True)

    base = models.ManyToManyField(Base, null=True, help_text='Select a base for this Brigade.')

    def __str__(self):
        """String for representing the Model object."""
        return self.name

    def get_absolute_url(self):
        """Returns the URL to access a detail record for this Brigade."""
        return reverse('brigade-detail', args=[str(self.id)])

class Battalion(models.Model):
    name = models.CharField(max_length=200, help_text='Enter the Battalion.')

    brigade = models.ForeignKey(Brigade, on_delete=models.RESTRICT, null=True)

    base = models.ManyToManyField(Base, help_text='Select a base for this Battalion.')

    def __str__(self):
        """String for representing the Model object."""
        return self.name

    def get_absolute_url(self):
        """Returns the URL to access a detail record for this Battalion."""
        return reverse('battalion-detail', args=[str(self.id)])

class Company(models.Model):
    name = models.CharField(max_length=200, help_text='Enter the Company.')

    battalion = models.ForeignKey(Battalion, on_delete=models.RESTRICT, null=True)

    base = models.ManyToManyField(Base, help_text='Select a base for this Battalion.')

    def __str__(self):
        """String for representing the Model object."""
        return (self.name + ", " + self.battalion.name)

    def get_absolute_url(self):
        """Returns the URL to access a detail record for this Company."""
        return reverse('company-detail', args=[str(self.id)])

def generate_filename():
    pass

class File(models.Model):
    name = models.CharField(max_length=200, help_text='Enter the file name.')
    file = models.FileField(upload_to="files/%Y/%m%d")
    base = models.ForeignKey(Base, on_delete=models.CASCADE, null=True, blank=True)
    command = models.ForeignKey(Command, on_delete=models.CASCADE, null=True, blank=True)
    brigade = models.ForeignKey(Brigade, on_delete=models.CASCADE, null=True, blank=True)
    battalion = models.ForeignKey(Battalion, on_delete=models.CASCADE, null=True, blank=True)
    company = models.ForeignKey(Company, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.name

app/templates/app/base_detail.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Name: {{ base.name }}</h1>

<p><strong>Location:</strong> {{ base.location }}</p>
<p><strong>Battalions:</strong></p>
{% if base.battalion_set %}
<ul>
    {% for battalion in base.battalion_set.all %}
    <li> 
        <a href="{{ battalion.get_absolute_url }}">{{ battalion.name }}</a>
    </li>
    {% endfor %}
</ul>
  {% else %}
<p>There are no battalions in the database.</p>
  {% endif %}
<p><strong>References:</strong></p>
{% if base.file_set %}
<ul>
    {% for file in base.file_set.all %}
    <li>
        <a href="{{ file.file.url }}">{{ file.name }}</a>
    </li>
    {% endfor %}
</ul>
  {% endif %}
{% endblock %}

app/templates/app/base_list.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Base List</h1>
  {% if base_list %}
<ul>
    {% for base in base_list %}
    <li>
        <a href="{{ base.get_absolute_url }}">{{ base.name }}</a> ({{base.location}})
    </li>
    {% endfor %}
</ul>
  {% else %}
<p>There are no bases in the database.</p>
  {% endif %}
{% endblock %}

app/templates/app/battalion_detail.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Name: {{ battalion.name }}</h1>

<p><strong>Brigade:</strong> {{ battalion.brigade.name }}</p>
<p><strong>Base:</strong> {{ battalion.base.all|join:", " }}</p>
<p><strong>Companys:</strong></p>
{% if battalion.company_set %}
<ul>
    {% for company in battalion.company_set.all %}
    <li>
        <a href="">{{ company.name }}</a> ({{company.base.all|join:", "}})
    </li>
    {% endfor %}
</ul>
  {% else %}
<p>There are no companies in the database.</p>
  {% endif %}
{% endblock %}

app/templates/app/battalion_list.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Battalion List</h1>
  {% if battalion_list %}
<ul>
    {% for battalion in battalion_list %}
    <li>
        <a href="{{ battalion.get_absolute_url }}">{{ battalion.name }}</a> ({{ battalion.base.all|join:", " }})
    </li>
    {% endfor %}
</ul>
  {% else %}
<p>There are no battalions in the database.</p>
  {% endif %}
{% endblock %}

app/templates/app/brigade_detail.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Name: {{ brigade.name }}</h1>
<p><strong>Base:</strong> {{ brigade.base.all|join:", " }}</p>
<p><strong>Companys:</strong></p>
{% if brigade.battalion_set %}
<ul>
    {% for battalion in brigade.battalion_set.all %}
    <li>
        <a href="{{ battalion.get_absolute_url }}">{{ battalion.name }}</a> ({{ battalion.base.all|join:", " }})
    </li>
    {% endfor %}
</ul>
  {% else %}
<p>There are no battalions in the database.</p>
  {% endif %}
{% endblock %}

app/templates/app/userprofile_form.html
{% extends "base_generic.html" %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />
</form>
{% endblock %}